apiVersion: v1
data:
  password: Y2F0YWxvZy1tb25nby1wYXNz
kind: Secret
metadata:
  creationTimestamp: null
  name: catalog-mongo-pass

---
apiVersion: v1
data:
  password: Y2FydC1yZWRpcy1wYXNz
kind: Secret
metadata:
  creationTimestamp: null
  name: cart-redis-pass

---
apiVersion: v1
data:
  password: b3JkZXItcG9zdGdyZXMtcGFzcw==
kind: Secret
metadata:
  creationTimestamp: null
  name: order-postgres-pass

---
apiVersion: v1
data:
  password: dXNlcnMtbW9uZ28tcGFzcw==
kind: Secret
metadata:
  creationTimestamp: null
  name: users-mongo-pass

---
apiVersion: v1
data:
  password: dXNlcnMtcmVkaXMtcGFzcw==
kind: Secret
metadata:
  creationTimestamp: null
  name: users-redis-pass